### ISSUE TITLE
Update Bower Version

### ISSUE THREAD

**Issue by jakofranko** [ondras/rot.js#105]
Bower uses your git tags for versioning, and the only tag you have right now is v0.5.0. It would be nice to get the most current version in order to take advantage of recent bug fixes (Looking at Array.prototype.randomize())...

**Comment by ondras** [comment]
Hi,

thanks, I forgot to push the git tag. Shall be fixed now.

**Comment by erikyuzwa** [comment]
confirmed for me anyways, now seeing `v0.6.0`. 👍

**Comment by jakofranko** [comment]
Me too! Thanks!
