### ISSUE TITLE
Problem with npm package

### ISSUE THREAD

**Issue by bkjohnson** [ondras/rot.js#117]
I ended up going with bower like you said in the readme, but I first tried with `npm` since I saw it published there so I thought I'd mention this.  When I installed rot using `npm` loading the file at `node_modules/rot-js/lib/rot.js` throws an error:

![image](https://user-images.githubusercontent.com/2008881/27362556-cbe60e20-55f4-11e7-9583-945cb620ec5a.png)

Specifically it is talking about [this line](https://github.com/ondras/rot.js/blob/a0345cb72e3d25fdedc49d81c892fc58c81a032c/node/node-export.js#L5)

Just thought I'd bring this to your attention.  So far I haven't had problems with the bower version.

**Comment by ondras** [comment]
The npm package is meant for NodeJS only. Browser users are supposed to simply include https://github.com/ondras/rot.js/blob/master/rot.min.js using a `<script>` node.

**Comment by bkjohnson** [comment]
Got it, thanks!
