### ISSUE TITLE
Can you re-publish this to npm?

### ISSUE THREAD

**Issue by camden** [ondras/rot.js#120]
I'd like to be able to use the latest version of this package in npm. Can you update please?

Thanks!

**Comment by ondras** [comment]
Re-published as 0.6.3. Cheers! :smile:

**Comment by drschwabe** [comment]
What is the package name?  There is no package.json in this repo's root.

**Comment by ondras** [comment]
Right, the package.json is generated on-the-fly via the Makefile.

The correct npm package name is [rot-js](https://www.npmjs.com/package/rot-js).

**Comment by camden** [comment]
Thanks @ondras!
