### ISSUE TITLE
Supporing Typematic rates

### ISSUE THREAD

**Issue by konijn** [ondras/rot.js#133]
Greetings!

In the days of PS/2 keyboards, pressed keys would by default repeat faster after holding them down 0.5 seconds, they would trigger 11 events per seconds until the key up.
More info:
http://www.tekweb.dk/manuals/command/commands/M/MODEST.HTM

Is it possible to emulate this in ROT.js ? (Keeping track of 'down'/'pressed' events for a key without a matching 'up'? This would make crossing larger screens so much more bearable.

If you were interested, but lack time, let me know and I might try and take a stab at it.

**Comment by kosinaz** [comment]
Check out https://github.com/kosinaz/Dungeons-of-Neverknown
I think this is what you are looking for.
It is not based on rot.js though.

**Comment by konijn** [comment]
That, and for other users looking here, just setting `mode con rate=31` in the console fixes my problem as well.
