### ISSUE TITLE
ROT.Map.Uniform only uses the set seed for rooms, not for corridors

### ISSUE THREAD

**Issue by konijn** [ondras/rot.js#135]
Greetings,

it would appear that the corridors do not use the seed from     
`ROT.RNG.setSeed( PP.game.seed * PP.game.level );`

An example is here:
http://konijn.github.io/project-pandora/

Just start a game by pressing 1, then hit control S to save, every time you reload game 1 , you will see the rooms and the player in the same spot, but the corridors are every time different.

**Comment by ondras** [comment]
This is caused by a collision with your own `ArrayRandom` function that conflicts with the rot.js-based one:

```
Array.prototype.random = function ArrayRandom(){
  return this[Math.floor(Math.random() * this.length)];
}
```

Removing this function of yours might completely solve your issue :-)

**Comment by konijn** [comment]
Oh my, you rock!!
