### ISSUE TITLE
Scheduling broken with Heap addition

### ISSUE THREAD

**Issue by ondras** [ondras/rot.js#181]
Hi @Syntacticlosure,

I am afraid your recent addition of min-heap completely broke the scheduling.
  1. unit tests  at `tests/` are failing,
  1. people are running into issues: https://twitter.com/mikemcmarvelous/status/1267221319478767616

Would you mind taking a look?

**Comment by Syntacticlosure** [comment]
Yes,i am looking for the problem.

**Comment by Syntacticlosure** [comment]
fix here : #182,
sorry,it's all my fault to upload untested codes.

**Comment by ondras** [comment]
Great, thanks for the extra-prompt fix!
