### ISSUE TITLE
eventque.js in the lib folder does not successfully import MinHeap

### ISSUE THREAD

**Issue by Jer1911** [ondras/rot.js#188]
Hi,

First off I want to say thank you for making this amazing library. Now on to my issue:
I notice that in /lib/eventque.js , you say:

import {MinHeap} from "./MinHeap";

Which in my case caused a 404 when testing locally. When I changed that line to this:

import { MinHeap } from "./MinHeap.js";

It now works as expected. Not sure if this was just a typo or if it was intended and I am just being dumb, so I thought I would mention it here. Again, thanks for your great work!

Best Regards,
Jeremy

**Comment by ondras** [comment]
Nice find! The code is generated by `tsc` and it is apparently able to import both extension-less *and* .js files. I will fix this.

**Comment by ondras** [comment]
Hi @Jer1911,

it should be fixed now. Please let me know if you run into further issues.
