### ISSUE TITLE
Basic game example

### ISSUE THREAD

**Issue by jcubic** [ondras/rot.js#198]
I was looking at my code pen demos and I've found my [Rouge-like game](https://codepen.io/jcubic/full/oMbgym). It was created as a base for a real game, also as a demo of my library [jQuery Terminal](https://terminal.jcubic.pl/). You may take a look, it simple game similar to the original rouge with gold and health potions that you can collect, experience, AC, levels, and enemies.

When I was writing this game I had a hard time reading the documentation and tutorials (not too difficult but it could be better). Maybe a fully working example (that is don't have too many elements) will help others. You can link to it if you want.

**Comment by ondras** [comment]
Hi Jakub,

thanks for the suggestion. I added a link to your game to rot.js's official RogueBasin page: http://roguebasin.com/index.php/Rot.js
