### ISSUE TITLE
Additional array polyfill functions causing errors with other libraries.

### ISSUE THREAD

**Issue by deisdestiny** [ondras/rot.js#46]
The array functions "Array.prototype.random" and "Array.prototype.randomize" are causing blocking issues when using ROT with other libraries. One example is the Babylon WebGL engine, but I have encountered this issue with other libraries as well.
I had to convert them to standalone methods and replace any instance of Array.random/randomize with a call to the functions. Upon removing them, everything works perfectly.

**Comment by ondras** [comment]
The problem was fixed in BabylonJS source.
