### ISSUE TITLE
bower package is corrupted

### ISSUE THREAD

**Issue by dnbard** [ondras/rot.js#48]
I've installed `rot` using bower: 
```bash
bower install rot.js --save
```

And got empty folder (with only one file): 
![empty folder](http://content.screencast.com/users/dnbard/folders/Jing/media/936814ed-d1f0-4b2f-8960-d2a1dfa71caf/2015-01-03_2237.png)

**Comment by ondras** [comment]
Interesting. I am unable to reproduce; my output (Ubuntu Linux) looks like this:

```
ondras@idefix:~/Desktop/0$ bower install rot.js --save
bower rot.js#*              not-cached git://github.com/ondras/rot.js.git#*
bower rot.js#*                 resolve git://github.com/ondras/rot.js.git#*
bower rot.js#*                download https://github.com/ondras/rot.js/archive/v0.5.0.tar.gz
bower rot.js#*                 extract archive.tar.gz
bower rot.js#*                resolved git://github.com/ondras/rot.js.git#0.5.0
bower rot.js#~0.5.0            install rot.js#0.5.0
bower                          no-json No bower.json file to save to, use bower init to create one
```

```
ondras@idefix:~/Desktop/0/bower_components/rot.js$ ll
total 152
drwxrwxr-x 2 ondras ondras   4096 Jan  3 21:40 ./
drwxrwxr-x 3 ondras ondras   4096 Jan  3 21:40 ../
-rw-rw-r-- 1 ondras ondras    727 Jan  3 21:40 .bower.json
-rw-rw-r-- 1 ondras ondras    422 Sep 11 11:15 bower.json
-rw-rw-r-- 1 ondras ondras 135229 Sep 11 11:15 rot.js
```

1) what bower version do you use?

2) try to `bower cache clean` before?

3) are the results different when not using the `--save` switch?

**Comment by dnbard** [comment]
Hello! Thanks for quick response. Looks like I had an issue with **bower** (and for some strange reason that issue was reproducible only on **rot.js**). 

So in case if someone need it I just installed fresh version of bower (but I'm pretty sure that I had it already), clean cache and installed rot.js 
```bash
npm install -g bower
bower cache clean
bower install rot.js --save
```
