### ISSUE TITLE
Manual contains &minus; instead of '-'

### ISSUE THREAD

**Issue by hogart** [ondras/rot.js#49]
For example, here: https://github.com/ondras/rot.js/blob/c7c5fe925e4dbab829adb02ab56ea1a7999d3e98/manual/pages/hex/indexing.html#L14.

I copied listed numbers and got a compiler error (`error CS1525: Unexpected symbol ```<internal>'` — yep, I'm trying something in Unity3D) which costs me about half an hour to trace. The problem is Unicode minus symbol instead of `-`. Since they both look quite the same in the monospaced fonts it is hard to spot.

Normally I vote both hands for proper typography characters wherever possible, but this seems an exception to me. If you agree, I'll make PR with suitable replaces.

**Comment by ondras** [comment]
I agree.

The main point of having proper minus glyphs was that they are properly (vertically) aligned with the corresponding "plus" glyph. However, since there are no longer any `(+1, -1)` pairs (implicit plus is omitted), this argument is void.
