### ISSUE TITLE
Screen scaling for tiled display

### ISSUE THREAD

**Issue by mauricio-fidalgo** [ondras/rot.js#52]
i think it would be a good idea to give the option to scale tile based games.

**Comment by ondras** [comment]
This is already possible. The `tileSet` option can be either HTML `<img>` tag or a `<canvas>` element, so you are free to adjust your tiles as necessary (by pre-drawing them scaled to a secondary canvas, for instance) before using them with rot.js.

**Comment by mauricio-fidalgo** [comment]
the way i did was
``
display.getContainer().getContext('2d').imageSmoothingEnabled = false;
display.getContainer().getContext('2d').scale(2,2);
``
it scales up the drawings without blurring the pixels for pixely art stuff.
i think you can close that topic now xD

**Comment by ondras** [comment]
Global canvas scaling might work fine for this particular case, but please keep in mind that:

1) this does not work for tiles mixed with text (text will be scaled as well),
2) canvas scaling breaks the `eventToPosition` computation.

**Comment by mauricio-fidalgo** [comment]
@ondras How does text and tiles works at the same time? the interactive guide gives me no clues how to manage it.
