### ISSUE TITLE
Manual does not work offline in Chrome

### ISSUE THREAD

**Issue by rmtew** [ondras/rot.js#58]
I use Windows 8.1, and the latest Chrome.

When I open the manual and click on a link like "Interactive Manual", it takes me to the directory that the manual is in.  I then have to click on "index.html" to open it.  This is because Chrome does not treat local web pages like a web site, and infer the existence of default pages - which to be fair is the prerogative of the web server.

Going to the Interactive Manual, clicking on "Map Creation" and having it open up and seeing "Maze", "Whatever" and "Dungeon", nothing happens when clicking on them.

**Comment by ondras** [comment]
There is very little I can do with that, read more at http://stackoverflow.com/questions/4819060/allow-google-chrome-to-use-xmlhttprequest-to-load-a-url-from-a-local-file . Basically using "file://" sucks and shall be evaded alltogether :)

For offline development, I would suggest using a local webserver (http://localhost).
