### ISSUE TITLE
rot causes NW to crash

### ISSUE THREAD

**Issue by drschwabe** [ondras/rot.js#59]
Has anyone tried using rot with NW.js ? (aka node-webkit)

My NW application was crashing and I pinpointed the problem to rot (not sure exactly where within rot however; and to be fair perhaps the problem is with NW). 

I found that if I include a ```var rot = require('rot-js') ``` and then do anything related to changing the NW window object the application will crash.  If rot is not included, changes to the NW window object happen AOK. 

For example, if you want to  change the size of the window in NW you do something like this: 

```
var gui = require('nw.gui'),
    win = gui.Window.get()
win.resizeTo(800, 600) //< this will crash the app if you also require('rot-js') somewhere
```
So perhaps some global conflict with "Window" ? 

Tested and definitely crashes with the latest NW.js v0.12.1 (based off of IO.js v1.2) 64 bit Linux build.  However, it doesn't crash on the alternate version; node-webkit 0.8.6 (based off Node v0.10, older Chromium)

**Comment by ondras** [comment]
I would say that @blinkdog, who did all the node-porting work, might be interested in this one.

The node shim indeed pollutes the global namespace with a `window` property (https://github.com/ondras/rot.js/blob/master/node/node-shim.js#L4), so a conflict is indeed possible. I am not sure whether this is the real cause, though.

On the other hand, I am not 100% convinced that we actually *need* to have a `window` global for `rot.js`. @drschwabe, are you able to build `rot.js` yourself, removing the linked line from the `node-shim.js` file in the process?

**Comment by drschwabe** [comment]
Okay that solved it!   I dunno how to build rot atm, but by commenting out the ```window = global; ``` (line 8 of the node version of rot.js or whatever npm is serving up) there is no more crashing with the latest NW.js :)

I ran a rot map gen function quickly to test it so, as far as I can tell rot works fine without that - at least in NW.js anyway.

**Comment by ondras** [comment]
Good to know, thanks. Once @blinkdog confirms that removing the window global does not break anything else, I will happily fix this in rot.js's repo.

**Comment by blinkdog** [comment]
> Good to know, thanks. Once @blinkdog confirms that removing
> the window global does not break anything else, I will happily fix
> this in rot.js's repo.

Following the trail of `window`, it seems the `ROT.Display` constructor uses the global `requestAnimationFrame` to kick off the rendering loop.

Because `raf.js` is protected with `if (typeof window != "undefined") {`, it should be possible to replace that `window = global` line in `node-shim` with a Node-specific version of `requestAnimationFrame`:

    global.requestAnimationFrame = function(cb) { return setTimeout(cb, 1000/60); };

And that should do the trick. Let me clean up my workspace a bit then I'll open up a PR.

**Comment by seanewest** [comment]
@blinkdog https://github.com/chrisdickinson/raf has a battle-tested shim for requestAnimationFrame

I could try to implement it in a PR if you wish?

**Comment by ondras** [comment]
Already fixed in https://github.com/ondras/rot.js/pull/60, closing.
