### ISSUE TITLE
Things I noticed in tile.js

### ISSUE THREAD

**Issue by blinkdog** [ondras/rot.js#61]
Line 31 begins:

	if (clearBefore) {
		var b = this._options.border;
		this._context.fillStyle = bg;

		if (this._options.tileColor) {this._context.clearRect(x*tileWidth, y*tileHeight, tileWidth, tileHeight);} else {
			this._context.fillRect(x*tileWidth, y*tileHeight, tileWidth, tileHeight);
		}

	}

`var b` is declared and initialized, but is not used anywhere. A similar declaration is found in `hex.js` and `rect.js`, where it actually does modify what is drawn. `tile.js` does not appear to use it.

`this._options.tileColor` is unique to this spot in `tile.js`. There is a `tileColorize` option initialized in `display.js` and discussed in the [rot.js Interactive Manual](http://ondras.github.io/rot.js/manual/#tiles). This `tileColorize` option is also used later in `tile.js` itself.

The formatting of the `if`-`else` around `tileColor` has an odd layout; else on the same line, but the else block is properly formatted beneath?

**Comment by blinkdog** [comment]
Not sure if this needs another issue...

There is no documentation for ROT.RNG.getWeightedValue() in the Interactive Manual.

Should this be opened as its own issue?

**Comment by ondras** [comment]
> There is no documentation for ROT.RNG.getWeightedValue() in the Interactive Manual.

Good point, will add this. No need to create a separate issue.

**Comment by ondras** [comment]
> var b is declared and initialized, but is not used anywhere. A similar declaration is found in hex.js and rect.js, where it actually does modify what is drawn. tile.js does not appear to use it.

Good find, can be removed.

> this._options.tileColor is unique to this spot in tile.js. There is a tileColorize option initialized in display.js and discussed in the rot.js Interactive Manual. This tileColorize option is also used later in tile.js itself.

Right, because of historical reasons, various `ROT.Display` implementations are not realized via inheritance, but using composition. So even if some options are highly specific to certain backend, they are - for the sake of completeness - defined in the top-level `ROT.Display` object. I am quite okay with this; do you suggest some change here?

> The formatting of the if-else around tileColor has an odd layout; else on the same line, but the else block is properly formatted beneath?

`git blame` explains that both the hanging "b" variable as well as this particular line are a contributed code: https://github.com/ondras/rot.js/blame/master/src/display/tile.js

Apparently, I was quite benevolent with the style of contributed code. But I value readability and consistency, so I will re-format and fix this.

**Comment by ondras** [comment]
> this._options.tileColor is unique to this spot in tile.js. There is a tileColorize option initialized in display.js and discussed in the rot.js Interactive Manual. This tileColorize option is also used later in tile.js itself.

Ah, sorry, I misread the name initially. I hope all is fixed now? :-)

**Comment by blinkdog** [comment]
> Ah, sorry, I misread the name initially. I hope all is fixed now? :-)

Yes, those changes look good! :-)

I'm working on a coverage test suite (about 33% finished now), so I'm going over almost all the code line-by-line.

I'll probably discover a handful of other small things, so let's keep this issue open for a little bit.
I'll report anything small (< ~12 lines) here. If it looks like something larger, I'll open a new issue for it.

Thanks for the quick fixes to `tile.js`! :-)

**Comment by ondras** [comment]
`getWeightedValue` example added.

**Comment by blinkdog** [comment]
There is a mismatch between the Interactive Manual and the code in the Uniform dungeon generator.

The Interactive Manual says:
> roomDugPercentage – algorithm stops after this fraction of map area has been filled with rooms; default = 0.2

`uniform.js` says:
> roomDugPercentage: 0.1, /* we stop after this percentage of level area has been dug out by rooms */

So, either the manual needs the correct default (0.1), or the code does (0.2) :-)

**Comment by ondras** [comment]
Fixed :-)

**Comment by blinkdog** [comment]
`ROT.Map.Rogue` extends `ROT.Map` and not `ROT.Map.Dungeon`:

    ROT.Map.Rogue.extend(ROT.Map); 

In a way, it makes sense. My first quick glance over the code, it doesn't seem to populate `this._rooms` or `this._corridors`, so it doesn't really meet the contract of `Dungeon`.

However, the Interactive Manual documents the `Rogue` algorithm in the Map creation / Dungeon section, so it might be a little confusing if someone expects a `Dungeon` and they don't actually get one.

This one may be one of the bigger ones that needs its own issue?

**Comment by blinkdog** [comment]
The Interactive Manual doesn't document the options for the `Rogue` generator.

**Comment by blinkdog** [comment]
I think there is a bug in the options processing in the `Rogue` constructor:

```javascript
	if (!this._options.hasOwnProperty("roomWidth")) {
		this._options["roomWidth"] = this._calculateRoomSize(this._width, this._options["cellWidth"]);
	}

	if (!this._options.hasOwnProperty["roomHeight"]) {
		this._options["roomHeight"] = this._calculateRoomSize(this._height, this._options["cellHeight"]);
	}
```

Look very carefully:
```javascript
    hasOwnProperty("roomWidth")
```
vs.
```javascript
    hasOwnProperty["roomHeight"]
```

The brackets [ ] instead of the parens ( ) cause the if-statement to always be true in the `roomHeight` case.

**Comment by blinkdog** [comment]
`Rogue` has it's own random number generator function
```javascript
ROT.Map.Rogue.prototype._getRandomInt = function(min, max) {
	return Math.floor(ROT.RNG.getUniform() * (max - min + 1)) + min;
}
```
that can probably be replaced by calls to `ROT.RNG.getUniformInt` instead :
```javascript
	getUniformInt: function(lowerBound, upperBound) {
		var max = Math.max(lowerBound, upperBound);
		var min = Math.min(lowerBound, upperBound);
		return Math.floor(this.getUniform() * (max - min + 1)) + min;
	},
```

**Comment by ondras** [comment]
Well, ROT.Map.Rogue is a 100% contributed code and I really have no idea how it works. Please submit a separate issue and I will try to adjust the code as necessary.

**Comment by blinkdog** [comment]
Okay, I'll collect all these `Rogue` observations in a new issue.

**Comment by blinkdog** [comment]
There is no documentation for map features in the Interactive Manual.

`ROT.Map.Feature`
`ROT.Map.Feature.Corridor`
`ROT.Map.Feature.Room`

**Comment by blinkdog** [comment]
There are a few spots in `feature.js` where `ROT.RNG.getUniformInt()` could be used instead of calculating the random value in-place.

`ROT.Map.Feature.Room.createRandomAt`
`ROT.Map.Feature.Room.createRandomCenter`
`ROT.Map.Feature.Room.createRandom`
`ROT.Map.Feature.Corridor.createRandomAt`

**Comment by ondras** [comment]
> There is no documentation for map features in the Interactive Manual.

Right, this is intentional.

The Interactive Manual is not an exhaustive listing of all features (the [autogenerated docs](http://ondras.github.io/rot.js/doc/) are), but a highlight of those that are most useful.

`ROT.Map.Feature` is an experimental and unstable interface. I would propose to leave it in its current state for now.

**Comment by ondras** [comment]
> There are a few spots in feature.js where ROT.RNG.getUniformInt() could be used instead of calculating the random value in-place.

Fair enough, these features were present long before the `getUniformInt` shortcut was implemented. Will fix this.

**Comment by blinkdog** [comment]
>ROT.Map.Feature is an experimental and unstable interface. I would propose to leave it in its current state for now.

Sounds good to me. Probably not a good idea to promote an API that is still intended to change significantly. :-)

**Comment by blinkdog** [comment]
Some spaces (not tabs) snuck in behind the declaration of _G2 in `src/noise/simplex.js`:
```javascript
ROT.Noise.Simplex = function(gradients) {
	ROT.Noise.call(this);

	this._F2 = 0.5 * (Math.sqrt(3) - 1);
    this._G2 = (3 - Math.sqrt(3)) / 6;

	this._gradients = [
		[ 0, -1],
```
Can't see it very well here on GitHub ... sorry about that.

**Comment by ondras** [comment]
> Some spaces (not tabs) snuck in behind the declaration of _G2 in src/noise/simplex.js:

Fixed: https://github.com/ondras/rot.js/commit/3af05caf8d9a9345587831ff4394e1a33ff8fa48

**Comment by blinkdog** [comment]
There is some inconsistency in the way the FOV algorithms use the output callback.

`ROT.FOV.DiscreteShadowcasting.prototype.compute`
* The first use of the callback (the "the origin is always visible" call) provides only three arguments instead of the standard four:

```javascript
ROT.FOV.DiscreteShadowcasting.prototype.compute = function(x, y, R, callback) {
	var center = this._coords;
	var map = this._map;

	/* this place is always visible */
	callback(x, y, 0);
```

`ROT.FOV.PreciseShadowcasting.prototype.compute`
* Sends visibility [0..1] as the fourth argument
* This is the documented behavior in the Interactive Manual; although the manual specifies "(0..1)" as opposed to [0..1]

`ROT.FOV.RecursiveShadowcasting.prototype.compute`
* Always sends `true` as the fourth argument

**Comment by blinkdog** [comment]
```javascript
/**
 * Compute visibility for a 180-degree arc
 * @param {int} x
 * @param {int} y
 * @param {int} R Maximum visibility radius
 * @param {int} dir Direction to look in (expressed in a ROT.DIR value);
 * @param {function} callback
 */
ROT.FOV.RecursiveShadowcasting.prototype.compute180 = function(x, y, R, dir, callback) {
```

```javascript
/**
 * Compute visibility for a 90-degree arc
 * @param {int} x
 * @param {int} y
 * @param {int} R Maximum visibility radius
 * @param {int} dir Direction to look in (expressed in a ROT.DIR value);
 * @param {function} callback
 */
ROT.FOV.RecursiveShadowcasting.prototype.compute90 = function(x, y, R, dir, callback) {
```

The @param for `dir` mentions `ROT.DIR`, but this should probably be `ROT.DIRS` in both cases.

**Comment by blinkdog** [comment]
In `ROT.Lighting` the constructor passes the options argument along to `setOptions`:

```javascript
ROT.Lighting.prototype.setOptions = function(options) {
	for (var p in options) { this._options[p] = options[p]; }
	if (options.range) { this.reset(); }
	return this;
}
```

This references `options.range` and causes an error if no `options` object was provided at construction time. I suggest maybe a guard to skip this reference, so that a `ROT.Lighting` can be constructed without providing explicit options (i.e.: using the default options)

**Comment by blinkdog** [comment]
There is an if-statement in `ROT.Lighting` that seems to be always true:
`if (!(key in emittingCells)) { emittingCells[key] = [0, 0, 0]; }`

`emittingCells` is defined locally as an empty object, and `this._lights` will never have duplicate keys.

```javascript
ROT.Lighting.prototype.compute = function(lightingCallback) {
	var doneCells = {};
	var emittingCells = {};
	var litCells = {};
 
	for (var key in this._lights) { /* prepare emitters for first pass */
		var light = this._lights[key];
		if (!(key in emittingCells)) { emittingCells[key] = [0, 0, 0]; }
 
		ROT.Color.add_(emittingCells[key], light);
	}
```

Perhaps just change that line to: `emittingCells[key] = [0, 0, 0];`

**Comment by blinkdog** [comment]
`ROT.Path.AStar` has unreachable break statements in the `_distance` function:

```javascript
ROT.Path.AStar.prototype._distance = function(x, y) {
	switch (this._options.topology) {
		case 4:
			return (Math.abs(x-this._fromX) + Math.abs(y-this._fromY));
		break;
 
		case 6:
			var dx = Math.abs(x - this._fromX);
			var dy = Math.abs(y - this._fromY);
			return dy + Math.max(0, (dx-dy)/2);
		break;
 
		case 8: 
			return Math.max(Math.abs(x-this._fromX), Math.abs(y-this._fromY));
		break;
	}
 
        throw new Error("Illegal topology");
}
```

The `return` statements just prior prevent the `break` statement from ever being executed.

**Comment by ondras** [comment]
> ROT.Path.AStar has unreachable break statements in the _distance function:

This is intentional. I like my `case` statements to always end/pair with their corresponding `break`, even if the code block inside returns.

**Comment by ondras** [comment]
> Perhaps just change that line to: emittingCells[key] = [0, 0, 0];

Fixed in https://github.com/ondras/rot.js/commit/868a042885dfbb2abf830eb139709930ba79d652, thanks!

**Comment by ondras** [comment]
> This references options.range and causes an error if no options object was provided at construction time. I suggest maybe a guard to skip this reference,

I added a guard in this commit: https://github.com/ondras/rot.js/commit/868a042885dfbb2abf830eb139709930ba79d652

Do you think it is sufficient?

**Comment by ondras** [comment]
> The @param for dir mentions ROT.DIR, but this should probably be ROT.DIRS in both cases.

Fixed: https://github.com/ondras/rot.js/commit/a7eb893b0b07345508a74f21db198c367473beab

**Comment by ondras** [comment]
> There is some inconsistency in the way the FOV algorithms use the output callback.

Shall be consistent now: https://github.com/ondras/rot.js/commit/aaca357e92957311fffbf1e13ee019b80bd23aef https://github.com/ondras/rot.js/commit/07ec62046d7ad4abdc418c29f6ab473a01e56af2

**Comment by ondras** [comment]
> This is the documented behavior in the Interactive Manual; although the manual specifies "(0..1)" as opposed to [0..1]

The (semi)openness of an interval seems to be problematic with respect to math notation. In my country, for instance, `<a, b)` can be often seen. I am not sure how much attention needs to be paid to this.

**Comment by blinkdog** [comment]
>> ROT.Path.AStar has unreachable break statements in the _distance function:
>
>This is intentional. I like my case statements to always end/pair with their corresponding break, even if the code block inside returns.

No problem. I rather like that pattern too, I just pointed it out because my coverage test was showing red for the break. No need to modify; the world won't end. :-)

**Comment by blinkdog** [comment]
>> This references options.range and causes an error if no options object was provided at construction time. I suggest maybe a guard to skip this reference,
>
> I added a guard in this commit: 868a042
>
> Do you think it is sufficient?

Yep! I think that looks good! :-)

**Comment by blinkdog** [comment]
>> This is the documented behavior in the Interactive Manual; although the manual specifies "(0..1)" as opposed to [0..1]
>
> The (semi)openness of an interval seems to be problematic with respect to math notation. In my country, for instance, <a, b) can be often seen. I am not sure how much attention needs to be paid to this.

That's interesting! I never really considered that there might be a different notation for open () vs. closed [] intervals other than the one I knew. Yeah, knowing that, it can probably be left alone. :-)

**Comment by blinkdog** [comment]
`ROT.Display.Term.computeSize` has height/width turned around:

```javascript
ROT.Display.Term.prototype.computeSize = function(availWidth, availHeight) {
	return [process.stdout.columns, process.stdout.rows];
}
```

This should be: `return [process.stdout.rows, process.stdout.columns];`

**Comment by blinkdog** [comment]
And now, finally(!), a look at the work that spawned all these micro-issues:

https://github.com/blinkdog/rot.js/tree/node-coverage

```bash
git clone https://github.com/blinkdog/rot.js
cd rot.js
git checkout node-coverage
make node
npm install
cake coverage
```

The Cakefile is hard-wired to launch `firefox --new-tab`, so if you don't have Mozilla Firefox installed, you may have to open the coverage report (`coverage/lcov-report/index.html`) in another browser.

There is a still a little work to be done; 15 commits (many of them quick fixes for micro-issues on this ticket; thanks for the fast work @ondras!) have to be merged in and then the tests updated to pass post-merge.

But, for now, since I'm brain-fried, check out the 467 tests and 98-99% coverage.

I'll do the merge, final cleanup, and pull request tomorrow. :-)

**Comment by ondras** [comment]
This sounds very cool! I will definitely have a look as soon as possible (the machine I am using now is git-less, so probably later today or tomorrow).

**Comment by blinkdog** [comment]
OK to close this issue?
I think everything was fixed except the `ROT.Map.Rogue` stuff, which all went to Issue #62.

**Comment by ondras** [comment]
> There are a few spots in feature.js where ROT.RNG.getUniformInt() could be used instead of calculating the random value in-place.
> 
> ROT.Map.Feature.Room.createRandomAt
> ROT.Map.Feature.Room.createRandomCenter
> ROT.Map.Feature.Room.createRandom
> ROT.Map.Feature.Corridor.createRandomAt

These are not done yet. I will close this issue once these four are adjusted (hopefully tomorrow).

**Comment by ZLester** [comment]
Whoops, I thought I had snagged all of them. I'll pull that later today.
