### ISSUE TITLE
Mouseless web page

### ISSUE THREAD

**Issue by techtonik** [ondras/rot.js#66]
Upon entering the main page I somehow expected the keyboard shortcuts to guide me around. =)

**Comment by ondras** [comment]
@techtonik Can you please elaborate a bit? What page, what shortcuts? http://ondras.github.io/rot.js/hp/ has only regular HTML links, they are tab-focusable and enter-activable...

**Comment by techtonik** [comment]
@ondras yes, the page a http://ondras.github.io/rot.js/hp/ but process '?' key to show current keyboard navigation and also highlight some letters in link menu to be one keypress away from following. Like here:

![image](https://cloud.githubusercontent.com/assets/515889/8155856/fe89a028-1350-11e5-8c25-d64c671d62ab.png)

**Comment by ondras** [comment]
I see. Well, there is nothing interactive on the page (except for those plain links) and HTML link elements (`<a>`) cannot have an accesskey/accelerator, as shown in your screenshot: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/accesskey. So I am really not sure what are we trying to achieve, with respect to the HTML platform. Perhaps the "?" key would open a simple alertbox that would explain that you might use "tab" for navigation?

**Comment by techtonik** [comment]
@ondras I expected a demo of `rot.js` capabilities right away from the first page. I thought it was capable of processing keyboard shortcuts.

**Comment by hogart** [comment]
Or you can use Vimperator or similar tool if you like mouseless navigation so much.

**Comment by techtonik** [comment]
Just wanted to play with `rot.js` features. Keyboard control is the primary stuff in roguelikes, so if this problem is not yet solved in browsers, it makes little sense to look further.

**Comment by ondras** [comment]
Well, the main page is not really a showcase of rot.js features. It does not even include `rot.js` itself! :-)

I agree that keyboard control is the primary stuff in roguelikes. But the mainpage is basically a responsive screenshot, not an interactive app. The only form of interactivity are those links - and those are proper, responsive, and accessible HTML link elements.

**Comment by techtonik** [comment]
I see. =)
