### ISSUE TITLE
Cellular with { topology: 6 } and display with { layout: "hex" } include malformed coordinates.

### ISSUE THREAD

**Issue by blinks** [ondras/rot.js#73]
```javascript
    var display = new ROT.Display({ layout: "hex" });
    var mapGen = new ROT.Map.Cellular(null, null, {
        topology: 6,
        born: [4, 5, 6],
        survive: [3, 4, 5, 6]
    });
```

If I then call `mapGen.create`, I get 1s where walls exist and 0s both in legal empty hexes _and in illegal locations_.  By the latter, I mean that if I have the display draw at each coordinate that comes out of the map, it'll have many overlapping hexes.

While a simple workaround for the walls is to only store 1s, that doesn't allow me to determine a good coordinate for placing the player.  I assume there's some good way to filter it on my end (perhaps only even/odd x coords should be accepted), but it'd be better if the map generator didn't output those coords.

**Comment by ondras** [comment]
Hi @blinks,
this looks like a fair issue. I will investigate.

**Comment by ondras** [comment]
Should be fixed in https://github.com/ondras/rot.js/commit/658a7b2b76b1d69633b8de06b13be56bd1ed31b8. @blinks, can you confirm please?

**Comment by blinks** [comment]
Confirmed!  Many thanks for the quick response.
