### ISSUE TITLE
npm releases not up to date

### ISSUE THREAD

**Issue by fritzy** [ondras/rot.js#81]
The documentation says I should be able to forceSquareRatio, which doesn't work from the npm release, but does for the rot.min.js download. I'd rather be able to rely on my my package.json file for managing libraries. Would you like help keeping this up to date?
##

**Comment by ondras** [comment]
Hi,

I just published a fresh npm update. Please let me know if this stuff works for you, as npm is still not the main way of distributing rot.js :)

**Comment by mattiascibien** [comment]
I tried it but whenever I do `require('rot-js')` node says it cannot find the module.

**Comment by ondras** [comment]
> I tried it but whenever I do require('rot-js') node says it cannot find the module.

You have to install the module first. Try `npm install rot-js --save` in your project's directory.

**Comment by mattiascibien** [comment]
@ondras I did it. Version 0.6.0 works without problems.

**Comment by mattiascibien** [comment]
@ondras I guess I did not installed it correctly. Today I seem to have 0.6.1 working. Sorry.

**Comment by seiyria** [comment]
If I install 0.6.1, I get an empty module as well. I noticed my builds started breaking and I could not figure out why. Have to revert to 0.6.0 to be able to use ROT.

**Comment by ondras** [comment]
I am not entirely sure what went wrong with 0.6.1. Please try npm updating to 0.6.2, this version works for me.
