### ISSUE TITLE
ROT.Display::eventToPosition(e) not working with transposed hex display

### ISSUE THREAD

**Issue by veswill3** [ondras/rot.js#94]
I saw issue #90 but I do not have the ability to reopen it. I am having trouble getting ROT.Display::eventToPosition(e) to work correctly with a transposed hex display. It is returning incorrect coordinates. I noticed that [ROT.Display.Hex.prototype.eventToPosition](https://github.com/ondras/rot.js/blob/e58e99f0033e819010e9d3d3187bb06539c3ae39/src/display/hex.js#L102) has code that accounts for the transpose flag, so I am not sure what is going wrong.

I created a jsfiddle to show the issue. You can verify that it works in normal mode by switching the `transpose` flag to `false`

https://jsfiddle.net/m0ba0ojg/

Please let me know if I made a mistake or if I am implementing this incorrectly. If not I would be happy to tinker with it and submit a pull request.

**Comment by veswill3** [comment]
I just noticed that if `height` and `width` of the display are the same then it works fine, which is why the test did not catch the issue.

**Comment by ondras** [comment]
Interesting, I will definitely have a look.

**Comment by ondras** [comment]
Confirming.

**Comment by ondras** [comment]
@veswill3 fixed just now :)

**Comment by veswill3** [comment]
Thanks for the quick update @ondras!
